In [2]:
print('hello world')

hello world


In [3]:
2+3*5+5

22

In [4]:
(2+3)*(3+5)

40

In [5]:
(2+3)*(5+5)

50

In [6]:
mite=100
print(mite)

100


In [7]:
print('the value of mite is',mite)

the value of mite is 100


In [8]:
mite

100

In [9]:
'Mangalore is nice place'

'Mangalore is nice place'

In [10]:
"mangalore is nice place"

'mangalore is nice place'

In [0]:
name=mite

In [12]:
"i can wrap lot's of code in this stream"

"i can wrap lot's of code in this stream"

In [14]:
num=22
name="mite"
print(num+1,name,"is the best plave to study")

23 mite is the best plave to study


In [21]:
print("my number is {one} and name is (two)".format(one=num,two=name))

my number is 22 and name is (two)


In [23]:
x=input("enter the first number")
y=input("enter the second number")
i=int(x)
j=int(y)
print("the product is",i*j)

enter the first number7
enter the second number23
the product is 161


In [26]:
x=input("enter the first number")
y=input("enter the second number")
i=float(x)
j=float(y)
print("the product is",i*j)

KeyboardInterrupt: ignored

In [27]:
x=input("enter the first number")
y=input("enter the second number")
i=bool(x)
j=bool(y)
print("the product is",i*j)

enter the first number0
enter the second number1
the product is 1


In [29]:
married=bool(input("Are you married? T/F"))

Are you married? T/FFalse


In [30]:
id=input(("Enter employee id"))
name=str(input("Enter employee name"))
basic_sal=float(input("enter basic salary"))
total_sal=1.25*basic_sal
Fre=bool(input("Whether the employee is fresher"))
print("id",id)
print("Name",name)
print("Salary",total_sal)
print("Fresher or not",Fre)

Enter employee id1234
Enter employee nameShalmali
enter basic salary10000
Whether the employee is fresherTrue
id 1234
Name Shalmali
Salary 12500.0
Fresher or not True


In [32]:
a,b=[float(x) for x in input("Enter 2 numbers").split()]
print("Product is:",a*b)

Enter 2 numbers2 4
Product is: 8


In [41]:
a,b,c=[float(x) for x in input("Enter 3 floatnumbers").split(',')]
print("Sum is:",a+b+c)

Enter 3 floatnumbers2,3,4
Sum is: 9.0


In [38]:
x=eval("10+20+30")
print(x)

60


In [39]:
x=eval("(10+20)+30/10*2")
print(x)

36.0


In [42]:
print("hello\nworld")
print("hello\tworld")

hello
world
hello	world


In [45]:
print(10*'hello')

hellohellohellohellohellohellohellohellohellohello


In [46]:
[1,2,3]

[1, 2, 3]

In [47]:
['hey',1,2,4]

['hey', 1, 2, 4]

In [48]:
[[0,1],1,2]

[[0, 1], 1, 2]

In [0]:
my_list=['a','b','c']

In [0]:
my_list.append('d')

In [51]:
my_list


['a', 'b', 'c', 'd']

In [52]:
my_list[0]

'a'

In [53]:
my_list[1:]

['b', 'c', 'd']

In [54]:
my_list[-2]

'c'

In [0]:
my_list='Shalmali'

In [55]:
my_list[:5]

['a', 'b', 'c', 'd']

In [0]:
my_list='Shalmali'


In [0]:
mylist=[1,2,3,[4,5],['shalmali']]

In [58]:
mylist

[1, 2, 3, [4, 5], ['shalmali']]

In [19]:
for j in range(0,4):
    if(i+j>=3):
        print("*",end=" ")
    else:
          print(" ",end=" ")
    print()


* 
* 
* 
* 


In [25]:
for i in range(0,4):
    for j in range(0,4):

        if i+j>=3:
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print( )

      * 
    * * 
  * * * 
* * * * 


In [26]:
s="virat"
d=list(s)

In [27]:
d


['v', 'i', 'r', 'a', 't']

In [31]:
s=input("Enter the name")
for x in range(len(s)):
    for y in range(0,x+1):
        print(s[x],end=" ")
    print()

Enter the nameshalmali
s 
h h 
a a a 
l l l l 
m m m m m 
a a a a a a 
l l l l l l l 
i i i i i i i i 


In [33]:
rec={}
n=int(input("Enter the number of students"))
i=1
while i<=n:
    name=input("Enter stuent name:")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
print("name of the student","\t","% of marks")
for x in rec:
    print("\t",x,"\t\t",rec[x])

Enter the number of students3
Enter stuent name:qwe
enter % marks of student111
Enter stuent name:qwe
enter % marks of student134
Enter stuent name:www
enter % marks of student121
name of the student 	 % of marks
	 qwe 		 134
	 www 		 121


In [34]:
d={100:"hello",2:"mite",300:"shalmali

In [35]:
d

{100: 'hello', 2: 'mite', 300: 'shalmali'}

In [36]:
d[400]="M"

In [37]:
d

{100: 'hello', 2: 'mite', 300: 'shalmali', 400: 'M'}

In [38]:
d[100]="hey"

In [39]:
d


{100: 'hey', 2: 'mite', 300: 'shalmali', 400: 'M'}

In [41]:
del d[2]

In [42]:
d

{100: 'hey', 300: 'shalmali', 400: 'M'}

In [44]:
d.clear() #delete temporarily

In [45]:
d

{}

In [46]:
del d #deleting permanently

In [47]:
d

NameError: name 'd' is not defined

In [49]:
di={100:"hello",2:"mite",300:"shalmali"}

In [50]:
di

{100: 'hello', 2: 'mite', 300: 'shalmali'}

In [53]:
len(di)

3

In [54]:
word=input("enter any word")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter any wordhheeellloooo
h occure 2 times
e occure 3 times
l occure 3 times
o occure 4 times


In [65]:
word=input("enter any word")
d={}

for x in word:
   
    if x =='a'or x =='e' or x =='i' or x =='o' or x =='u':
         d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter any wordaeiouu
a occure 1 times
e occure 1 times
i occure 1 times
o occure 1 times
u occure 2 times


In [66]:
word=input("enter any word")#   wwwwwwwwwwwwwrrrrrrrrrrrrooooooonnnnnggggggggggggggg
d={}
vowels={'a','e','i','o','u'}
for x in word:
   
    for x in vowels:
         d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter any wordshalmali
i occure 8 times
o occure 8 times
a occure 8 times
e occure 8 times
u occure 8 times


In [67]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [68]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))

4


In [70]:
print(n.index(2))

1


In [73]:
n=[1,2,3,4,5]
n.insert(1,888)#insert(index,value to be inserted)
print(n)

[1, 888, 2, 3, 4, 5]


In [74]:
n2=[1,2,3,"hello"]
n.extend(n2)

In [75]:
print(n)

[1, 888, 2, 3, 4, 5, 1, 2, 3, 'hello']


In [76]:
n2

[1, 2, 3, 'hello']

In [77]:
n

[1, 888, 2, 3, 4, 5, 1, 2, 3, 'hello']

In [79]:
n.remove(2)

###remove function

In [80]:
n

[1, 888, 3, 4, 5, 1, 3, 'hello']

In [81]:
n.pop()

'hello'

In [82]:
n.reverse()

In [83]:
n


[3, 1, 5, 4, 3, 888, 1]

In [89]:
l1=["shalmali","rishika","gahana","disha"]
l1.sort()

In [90]:
l1.sort(reverse=True)#sorting in for reverse order

In [91]:
l1

['shalmali', 'rishika', 'gahana', 'disha']

In [88]:
l1

['shalmali', 'rishika', 'gahana', 'disha', 100, 60, 20, 81]

In [85]:
l1

['disha', 'gahana', 'rishika', 'shalmali']

In [95]:

x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [96]:
###copy by reference
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [97]:
###copy by value
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [100]:
a=[10,20,30,40]
b=[50,60,70]
c=a+b
print(c)


[10, 20, 30, 40, 50, 60, 70]


In [101]:
x=[10,20,30,40]
y=x*3   #.....* is a repeatation operator
print(y)

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]


In [102]:
x=["mite","nitte"]
y=["mite","nitte"]
x==y

True

In [103]:
x!=y

False

In [105]:
z=["mite","nte"]
x==z

False

In [109]:
m=[10,20,30,40,[50,60,70]]
m[2]



30

In [110]:
m[4][1]


60

In [111]:
m.clear()


In [112]:
m

[]

In [113]:
n=[1,2,3,4]
print(4 in n)

True


In [114]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [115]:
words=["mite","mysore","shalmali"] #To print the starting character of items in the list
l=[w[0] for w in words]
print(l)

['m', 'm', 's']


In [119]:
def pri_num(num):
    if i in range(2,num):
        if num%i==0:
            print("is prime")
        else:
            print("is not prime")
num=input("enter the number")
print(pri_num(num))


enter the number3


TypeError: 'str' object cannot be interpreted as an integer

In [125]:
flag=0
for i in range(2,n):
    if n%i==0:
        flag=1
        if flag==1:
            return 'Not a Prime'
        else:
            return 'Prime'
print(pr)

SyntaxError: 'return' outside function (<ipython-input-125-57fa76a69cd7>, line 6)

In [120]:
def times2(var):
    return var*2
seq=[1,2,3,4,5]
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [128]:
seq=[1,2,3,4,5]

lambda var: var*2
    
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [130]:
seq=[1,2,3,4,5]

lambda var: var*2
    
list(map(lambda var:var*2,seq))

list(filter(lambda item:item%2==0,seq))

[2, 4]

In [133]:
import numpy as np
my_list=[1,2,3]
my_list


[1, 2, 3]

In [135]:
np.array(my_list)

array([1, 2, 3])

In [136]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [137]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [141]:
np.zeros(3)

array([0., 0., 0.])

In [142]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [148]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [151]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [152]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [153]:
np.random.rand(2)

array([0.92679564, 0.81263293])

In [155]:
np.random.rand(5,5)

array([[0.65453381, 0.92994841, 0.92971987, 0.41862749, 0.69919208],
       [0.6449283 , 0.75190156, 0.32958457, 0.29507137, 0.71256354],
       [0.6944489 , 0.51881264, 0.42080174, 0.19950612, 0.91925263],
       [0.07303312, 0.54315793, 0.08012431, 0.4716406 , 0.9852884 ],
       [0.76443592, 0.26192795, 0.53397725, 0.15265041, 0.05979434]])

In [157]:
np.random.randn(5,5)#follows negative distibution

array([[-0.06250564,  1.53570736,  1.12515175, -0.02808765, -1.55500088],
       [ 0.78561105, -0.09792131, -0.23901449, -0.3653791 ,  0.26445969],
       [-0.90602046, -0.58734027,  0.61368699, -0.79492375, -0.62018042],
       [ 1.00644602, -1.55885124,  2.34968216,  1.81245548, -0.26191928],
       [-1.49271215, -0.45565864, -1.16062123, -0.94584324,  1.78869543]])

In [158]:
np.random.randint(1,100,10)#ten random numbers between 1 to 100

array([39, 67, 85, 65, 87, 60, 70,  9, 21, 93])

In [159]:
ar=np.random.randint(1,100,10)#storing the values in a variable 'ar'
ar

array([55, 35, 63, 80, 90, 42, 85, 90, 18, 61])

In [160]:
arr=np.arange(25)  #to arrange these random number into an array
arunarr=np.random.randint(0,50,10)
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [161]:
arunarr.max()

49

In [162]:
arunarr.argmax()

6

In [166]:
arunarr.min()

4

In [164]:
arunarr.argmin()

9

In [167]:
arr.shape

(25,)

In [168]:
arr.reshape(1,25)#1 row 2 column

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [169]:
arr.reshape(1,25).shape

(1, 25)

In [170]:
arr.reshape(25,1)#25 rows 1 column


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [171]:
arr.reshape(25,1).shape

(25, 1)

In [172]:
arr.dtype

dtype('int32')

In [173]:
arr=np.arange(0,10) #addition od array 
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [174]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [175]:
arr/arr

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [176]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [178]:
arr=np.arange(0,10)

In [179]:
1/arr

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [180]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [181]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [183]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [184]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [185]:
np.log(arr)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [186]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [188]:
arr[8]

8

In [189]:
arr[1:5]

array([1, 2, 3, 4])

In [190]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [193]:
arr[0:5]=100 #values will be 100 from 0 to 5-1=4
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [194]:
arr=np.arange(0,11)
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [195]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [196]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [197]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [199]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [200]:
arr=np.ones(15)*5

In [201]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [208]:
arr=np.arange(10,81,2)


In [209]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [212]:
np.random.rand(25)

array([0.45233199, 0.84859273, 0.97673667, 0.4569651 , 0.92746372,
       0.10921667, 0.08485234, 0.45355479, 0.19153814, 0.37876223,
       0.23338036, 0.9196771 , 0.17643987, 0.21129997, 0.07142635,
       0.31054939, 0.40346255, 0.28043634, 0.14835285, 0.34397897,
       0.1071043 , 0.78241964, 0.52904573, 0.86384695, 0.33362223])

In [215]:
arr=np.arange(8)  #to arrange these random number into an array
arunarr=np.random.randint(0,8)
arr.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels=['a','b','c']

In [4]:
my_array=[10,20,30]
pd.Series(data=my_array)

0    10
1    20
2    30
dtype: int64

In [5]:
my_array=[10,20,30]
pd.Series(data=my_array,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
my_array=[10,20,30]
pd.Series(my_array,labels)

a    10
b    20
c    30
dtype: int64

In [19]:
d={'a':10,'b':20,'c':30}
s1=pd.Series(d)

In [9]:
d={'a':10,'b':20,'c':30}
pd.Series([sum,len,print])

0      <built-in function sum>
1      <built-in function len>
2    <built-in function print>
dtype: object

In [24]:
d1={'usa':1,'russia':2,'Ukraine':3,'England':4}
s3=pd.Series(d1)

In [11]:
d['usa']

1

In [12]:
d2={'usa':5,'russia':6,'japan':7,'England':8}


In [18]:
s2=pd.Series(d2)

In [25]:
s3+s2

England    12.0
Ukraine     NaN
japan       NaN
russia      8.0
usa         6.0
dtype: float64

In [ ]:
#NaN=not a number

In [26]:
s3-s2

England   -4.0
Ukraine    NaN
japan      NaN
russia    -4.0
usa       -4.0
dtype: float64

In [27]:
from numpy.random import randn
np.random.seed(101)#seed is used toget same random numebr 

In [28]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())#.....dataframe

In [29]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [30]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [31]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [32]:
df.W #....SQL WAY OF APPRAOACHING

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [33]:
pandas.core.series.Series

NameError: name 'pandas' is not defined

In [35]:
df['new']=df['W']+df['Y']

In [36]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [37]:
df.drop('new',axis=1)#x axis=0,y axis=1,this will not delete it permanently,only for the out put it will get deleted

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [39]:
df.drop('new',axis=1,inplace=True)#inplace will delete it permanently

In [40]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [41]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [42]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [43]:
ddf.drop('E',axis=1,inplace=True)

KeyError: "['E'] not found in axis"

In [44]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [45]:
df.loc['A']
#selecting rows

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [46]:
df.iloc[2]#using index

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [47]:
df.loc['B','Y']

-0.8480769834036315

In [48]:
df.loc[['A','B'],['W','Y']]#grids

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [49]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [50]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [57]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [58]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [60]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [62]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [64]:
# RESET THE INDEX 0,1...n index
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [65]:
newind='CA NY WY OR CO'.split()#new column

In [67]:
df['states']=newind#index is states

In [68]:
df

W         X         Y         Z states
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [70]:
df.set_index('states')

W         X         Y         Z
states                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [72]:
df.set_index('states',inplace=True)


In [73]:
df

W         X         Y         Z
states                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [75]:
#Multi-indexing
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))#....zip is a function used to combine two indices
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [76]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [77]:
df=pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [78]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [79]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [80]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [ ]:
#frozen list=index created once cannot be changed by anyone else,but can change by only the person created it

In [81]:
df.index.names=['Group','Num']

In [82]:
df

A         B
Group Num                    
G1    1    0.302665  1.693723
      2   -1.706086 -1.159119
      3   -0.134841  0.390528
G2    1    0.166905  0.184502
      2    0.807706  0.072960
      3    0.638787  0.329646

In [83]:
df.xs('G1')#XS=CROSSECTION

A         B
Num                    
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [86]:
df.xs(['G1',1])

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [87]:
df.xs(1,level='Num')

A         B
Group                    
G1     0.302665  1.693723
G2     0.166905  0.184502

In [103]:
for x in range(0,4):
    for y in range(0,8):
        if x+y==3 or x+y==5 or x+y==5 or x+y==7 or x+y==9:
            print('*',end=" ")
        else:
            print(" ",end=" ")
    print()


      *   *   * 
    *   *   *   
  *   *   *   * 
*   *   *   *   


In [107]:
n=int(input("enter the number of rows required"))
for i in range(1,n+1):
    print(" "*(n-i),"*"*(2*i-1))

enter the number of rows required4
    *
   ***
  *****
 *******


In [110]:
df=pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]})

In [111]:
df


A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [112]:
df.dropna()
df


A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [113]:
df.dropna()#remove nan values

A    B  C
0  1.0  5.0  1

In [114]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [115]:
df.dropna(thresh=2)#till n=2

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [116]:
df.fillna(value='FILL VALUE')

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [117]:
df['A'].fillna(value=df['A'].mean())#filling the fill value with mean 

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [ ]:
#loading csv file

In [119]:
df=pd.read_csv('example')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [120]:
pd.read_excel('Excel_Sample.xlsx',sheetname='Sheet1')

C:\Users\user\Anaconda3\lib\site-packages\pandas\io\excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)


a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [122]:
df=pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [123]:
df

[                                             Bank Name                City  \
 0                                 The Enloe State Bank              Cooper   
 1                  Washington Federal Bank for Savings             Chicago   
 2      The Farmers and Merchants State Bank of Argonia             Argonia   
 3                                  Fayette County Bank          Saint Elmo   
 4    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 5                                       First NBC Bank         New Orleans   
 6                                        Proficio Bank  Cottonwood Heights   
 7                        Seaway Bank and Trust Company             Chicago   
 8                               Harvest Community Bank          Pennsville   
 9                                          Allied Bank            Mulberry   
 10                        The Woodbury Banking Company            Woodbury   
 11                              First CornerStone B

In [124]:
import pandas as pd
df=pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()


col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [125]:
df['col2'].unique()#unique values

array([444, 555, 666], dtype=int64)

In [126]:
df['col2'].nunique()#number of unique values

3

In [127]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [128]:
newdf=df[(df['col1']>2)&(df['col2']==444)]

In [129]:
newdf

col1  col2 col3
3     4   444  xyz

In [130]:
def times2(x):
    return x*2


In [131]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [134]:
df


col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [136]:
df['col1'].len()

AttributeError: 'Series' object has no attribute 'len'

In [137]:
df['col1'].sum()

10

In [138]:
del df['col1']

In [139]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [141]:
df['col2'].apply(len)

TypeError: object of type 'int' has no len()

In [142]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [143]:
df.sort_values(by='col2')

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [145]:
df.isnull()#to check if any value is null,idf so then displays to or else displays false

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [147]:
df=pd.read_csv('Ecommerce Purchases')
df

Address    Lot AM or PM  \
0     16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1     9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                      Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3                 7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4     23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   
5     7502 Powell Mission Apt. 768\nTravisland, VA 3...  21 XT       PM   
6        93971 Conway Causeway\nAndersonburgh, AZ 75107  96 Xt       AM   
7     260 Rachel Plains Suite 366\nCastroberg, WV 24...  96 pG       PM   
8               2129 Dylan Burg\nNew Michelle, ME 28650  45 JN       PM   
9       3795 Dawson Extensions\nLake Tinafort, ID 88739  15 Ug       AM   
10        650 Elizabeth Park\nLake Maria, LA 13526-2530  65 Yn       PM   
11               349 Laurie Parks\nThomasview, ID 08970  30 kK       PM   
12      733 Heather Rest Apt. 670\nBoltonport, UT 78662  69 DO       AM   
13    118 Melton Via Suite 681\nAlexanderbury, FL 32104  36 bu       PM   
14    8774 Jason Keys Suite 427\nEast Scottborough, ...  70 zH       AM   
15       31730 Chelsea Crest\nBlakemouth, CT 90395-0620  41 Cj       PM   
16    5283 Thomas Trafficway Suite 343\nEast Brittne...  31 ho       AM   
17    950 Jacqueline Village Apt. 592\nPort Kimberly...  23 Rh       PM   
18    461 Christopher Square\nWest Michaelchester, C...  17 SB       PM   
19                  125 Hall Summit\nBoothton, IL 41721  99 CU       PM   
20        7383 George Village\nLake Jamesview, CO 79828  23 dk       PM   
21    282 Miller Valleys Suite 404\nWilkinsonbury, M...  24 RZ       AM   
22     625 Laura Summit Suite 112\nShortmouth, AK 97156  45 oa       PM   
23    25292 Shepherd Trail Apt. 798\nRussellmouth, S...  31 pS       PM   
24                Unit 3046 Box 3197\nDPO AE 61496-4172  62 Ac       AM   
25    80797 Ryan Trail Apt. 752\nAaronhaven, MI 0622...  66 SO       PM   
26          5334 Sheppard Fort\nNorth Kirsten, ND 71170  40 ND       AM   
27           5015 Smith Harbors\nSouth Ashley, OK 81283  34 JQ       PM   
28    50533 Cooper Cliffs\nNorth Jonathanberg, MD 20482  17 kP       PM   
29    30755 Joshua Plaza Apt. 567\nWest Susanton, FM...  93 OP       PM   
...                                                 ...    ...      ...   
9970              0060 Keith Stream\nWestport, CO 47097  11 nt       PM   
9971  5806 Martinez Point\nLake Abigailstad, MD 6183...  07 wl       AM   
9972  89504 Flynn Overpass Suite 822\nNew Elijah, WV...  23 eL       AM   
9973     92126 Daniel Streets\nNorth Patricia, IA 10477  04 QN       PM   
9974     500 Powell Rapid Apt. 114\nClarkfort, FL 70488  48 is       AM   
9975  5208 Hanson Trail Suite 527\nSouth Jonathanshi...  67 OX       PM   
9976  5419 Cruz Island Apt. 033\nLake Todd, AK 24863...  93 FM       PM   
9977  02182 Keith Expressway\nEast Shannon, CT 20578...  34 RL       AM   
9978   991 Watts Court\nSouth Danielstad, IA 39032-8865  66 eb       AM   
9979  00490 Joseph Haven Apt. 149\nWest Keithfurt, S...  69 XK       PM   
9980           6061 Dave Lights\nPhillipsview, UT 40500  25 Mv       AM   
9981  087 Larson Roads Apt. 587\nRicestad, WI 98077-...  95 Kw       AM   
9982  18044 Mcintosh Row Apt. 122\nLake Jennifer, NC...  77 uq       PM   
9983              PSC 5678, Box 4503\nAPO AP 94998-5546  79 cd       AM   
9984       7560 Boyle Keys\nAntoniomouth, DC 00522-0367  72 Qb       AM   
9985              7456 Stevens Rest\nEricside, FL 16389  27 Yv       PM   
9986  2719 Troy Drive Suite 062\nLisachester, PW 414...  80 Wl       PM   
9987     2754 Klein Mission\nJohnsonview, PA 64925-9624  65 Fg       PM   
9988      0154 Green Forest\nNew Timothy, IL 33670-4620  11 MC       AM   
9989         5674 Cruz Trace\nNew Shelby, KY 51047-5469  12 Kf       AM   
9990  75731 Molly Springs\nWest Danielle, VT 96934-5102  93 ty       PM   
9991              PSC 8165, Box 8498\nAPO AP 60327-0346  50 dA       AM  

In [149]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
'Sales':[200,120,340,124,243,350]}


In [150]:
df=pd.DataFrame(data)

In [151]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [155]:
df.groupby('Company')

In [157]:
by_comp=df.groupby('Company')

In [158]:
by_comp

In [159]:
by_comp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [160]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [161]:
df.groupby('Company').std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [162]:
df.groupby('Company').min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [163]:
df.groupby('Company').max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [164]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [165]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [168]:
by_comp.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

In [169]:
df=pd.read_csv('Ecommerce Purchases')
df

Address    Lot AM or PM  \
0     16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1     9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                      Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3                 7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4     23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   
5     7502 Powell Mission Apt. 768\nTravisland, VA 3...  21 XT       PM   
6        93971 Conway Causeway\nAndersonburgh, AZ 75107  96 Xt       AM   
7     260 Rachel Plains Suite 366\nCastroberg, WV 24...  96 pG       PM   
8               2129 Dylan Burg\nNew Michelle, ME 28650  45 JN       PM   
9       3795 Dawson Extensions\nLake Tinafort, ID 88739  15 Ug       AM   
10        650 Elizabeth Park\nLake Maria, LA 13526-2530  65 Yn       PM   
11               349 Laurie Parks\nThomasview, ID 08970  30 kK       PM   
12      733 Heather Rest Apt. 670\nBoltonport, UT 78662  69 DO       AM   
13    118 Melton Via Suite 681\nAlexanderbury, FL 32104  36 bu       PM   
14    8774 Jason Keys Suite 427\nEast Scottborough, ...  70 zH       AM   
15       31730 Chelsea Crest\nBlakemouth, CT 90395-0620  41 Cj       PM   
16    5283 Thomas Trafficway Suite 343\nEast Brittne...  31 ho       AM   
17    950 Jacqueline Village Apt. 592\nPort Kimberly...  23 Rh       PM   
18    461 Christopher Square\nWest Michaelchester, C...  17 SB       PM   
19                  125 Hall Summit\nBoothton, IL 41721  99 CU       PM   
20        7383 George Village\nLake Jamesview, CO 79828  23 dk       PM   
21    282 Miller Valleys Suite 404\nWilkinsonbury, M...  24 RZ       AM   
22     625 Laura Summit Suite 112\nShortmouth, AK 97156  45 oa       PM   
23    25292 Shepherd Trail Apt. 798\nRussellmouth, S...  31 pS       PM   
24                Unit 3046 Box 3197\nDPO AE 61496-4172  62 Ac       AM   
25    80797 Ryan Trail Apt. 752\nAaronhaven, MI 0622...  66 SO       PM   
26          5334 Sheppard Fort\nNorth Kirsten, ND 71170  40 ND       AM   
27           5015 Smith Harbors\nSouth Ashley, OK 81283  34 JQ       PM   
28    50533 Cooper Cliffs\nNorth Jonathanberg, MD 20482  17 kP       PM   
29    30755 Joshua Plaza Apt. 567\nWest Susanton, FM...  93 OP       PM   
...                                                 ...    ...      ...   
9970              0060 Keith Stream\nWestport, CO 47097  11 nt       PM   
9971  5806 Martinez Point\nLake Abigailstad, MD 6183...  07 wl       AM   
9972  89504 Flynn Overpass Suite 822\nNew Elijah, WV...  23 eL       AM   
9973     92126 Daniel Streets\nNorth Patricia, IA 10477  04 QN       PM   
9974     500 Powell Rapid Apt. 114\nClarkfort, FL 70488  48 is       AM   
9975  5208 Hanson Trail Suite 527\nSouth Jonathanshi...  67 OX       PM   
9976  5419 Cruz Island Apt. 033\nLake Todd, AK 24863...  93 FM       PM   
9977  02182 Keith Expressway\nEast Shannon, CT 20578...  34 RL       AM   
9978   991 Watts Court\nSouth Danielstad, IA 39032-8865  66 eb       AM   
9979  00490 Joseph Haven Apt. 149\nWest Keithfurt, S...  69 XK       PM   
9980           6061 Dave Lights\nPhillipsview, UT 40500  25 Mv       AM   
9981  087 Larson Roads Apt. 587\nRicestad, WI 98077-...  95 Kw       AM   
9982  18044 Mcintosh Row Apt. 122\nLake Jennifer, NC...  77 uq       PM   
9983              PSC 5678, Box 4503\nAPO AP 94998-5546  79 cd       AM   
9984       7560 Boyle Keys\nAntoniomouth, DC 00522-0367  72 Qb       AM   
9985              7456 Stevens Rest\nEricside, FL 16389  27 Yv       PM   
9986  2719 Troy Drive Suite 062\nLisachester, PW 414...  80 Wl       PM   
9987     2754 Klein Mission\nJohnsonview, PA 64925-9624  65 Fg       PM   
9988      0154 Green Forest\nNew Timothy, IL 33670-4620  11 MC       AM   
9989         5674 Cruz Trace\nNew Shelby, KY 51047-5469  12 Kf       AM   
9990  75731 Molly Springs\nWest Danielle, VT 96934-5102  93 ty       PM   
9991              PSC 8165, Box 8498\nAPO AP 60327-0346  50 dA       AM  

In [170]:
df.describe()

Credit Card  CC Security Code  Purchase Price
count  1.000000e+04      10000.000000    10000.000000
mean   2.341374e+15        907.217800       50.347302
std    2.256103e+15       1589.693035       29.015836
min    6.040186e+10          0.000000        0.000000
25%    3.056322e+13        280.000000       25.150000
50%    8.699942e+14        548.000000       50.505000
75%    4.492298e+15        816.000000       75.770000
max    6.012000e+15       9993.000000       99.990000

In [173]:
df.mean()

Credit Card         2.341374e+15
CC Security Code    9.072178e+02
Purchase Price      5.034730e+01
dtype: float64

In [175]:
df.max()

Address                              Unit 9991 Box 3616\nDPO AA 99399
Lot                                                             99 zl
AM or PM                                                           PM
Browser Info        Opera/9.99.(X11; Linux x86_64; it-IT) Presto/2...
Company                                                 Zuniga-Watson
Credit Card                                          6011999761615928
CC Exp Date                                                     12/25
CC Security Code                                                 9993
CC Provider                                                   Voyager
Email                                                zyoung@yahoo.com
Job                                                      Youth worker
IP Address                                               99.96.230.38
Language                                                           zh
Purchase Price                                                  99.99
dtype: object

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
Address             10000 non-null object
Lot                 10000 non-null object
AM or PM            10000 non-null object
Browser Info        10000 non-null object
Company             10000 non-null object
Credit Card         10000 non-null int64
CC Exp Date         10000 non-null object
CC Security Code    10000 non-null int64
CC Provider         10000 non-null object
Email               10000 non-null object
Job                 10000 non-null object
IP Address          10000 non-null object
Language            10000 non-null object
Purchase Price      10000 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [177]:
df['Purchase Price'].mean()

50.34730200000025

In [178]:
df['Purchase Price'].max()

99.99

In [179]:
df['Purchase Price'].min()

0.0

In [180]:
df.sort_values(by='Purchase Price')

Address    Lot AM or PM  \
5487     465 Mallory Ways\nNorth Rebecca, RI 82734-1160  93 OH       PM   
2876  332 Jones Parkways\nEast Katherineville, GA 64230  39 GT       AM   
6863     9202 Baker Forks\nNew Chelseaborough, VA 70852  40 Vx       AM   
8656          146 Laura Mission\nNorth Donald, NC 76608  95 xb       PM   
2783  402 Joseph Tunnel Apt. 219\nMartinmouth, DE 58480  46 Yg       AM   
550                    Unit 9279 Box 5039\nDPO AP 86638  40 Ai       PM   
6647         86103 Ricky Manor\nNunezton, VI 03206-5280  69 MM       PM   
4280  827 Kathryn Rest Suite 059\nGouldside, PA 4949...  04 ER       PM   
8937  964 Warren Village Apt. 836\nPort Amystad, NE ...  26 ex       AM   
2657  9682 Abigail Bridge\nEast Michaelland, DC 8825...  68 yk       AM   
8731  5687 Bradley Plaza Suite 396\nPort Melissa, DE...  35 eY       AM   
1530  402 Melissa Manors\nSouth Wendyville, OR 89088...  13 PQ       AM   
1691  52455 Rivas Divide\nNew Anthonyton, WA 35736-9050  55 NL       AM   
2438  94674 Obrien Circle Suite 912\nSouth Shane, ID...  10 Mz       AM   
9642          08054 Michael Common\nJonestown, KY 26310  66 fU       AM   
3882  6645 Samantha Mountains Suite 996\nEast Travis...  67 jI       PM   
5156  258 Clark Hills Suite 703\nLake Carolynstad, N...  79 Wa       PM   
366           802 Andrews Glens\nPatrickmouth, WA 78749  21 NN       AM   
1650     58371 Carolyn Path\nShannonstad, IN 06467-6721  74 hM       AM   
1154  58903 Tammy Knolls Suite 270\nBryantbury, VA 4...  34 PH       AM   
9694    076 Villanueva Trail\nLake Jacob, MN 50996-3395  35 Ri       AM   
3312  7419 Miles Roads Apt. 710\nNorth Christopherfu...  19 No       PM   
2418  82697 Susan Ville Suite 999\nSouth John, MA 63235  77 vq       AM   
6620  4946 Kelley Lodge Suite 926\nEast Christina, N...  95 Bq       AM   
559    4408 Cassidy Overpass\nSouth Beth, AK 68295-4309  55 QO       AM   
1021  8100 Johnson Rue\nNorth Jamiechester, KS 76665...  93 dI       AM   
9704           603 Tran Alley\nDuffyview, MD 99742-9731  05 hI       PM   
6083                   Unit 5879 Box 8138\nDPO AP 55602  04 cj       PM   
1221          780 Taylor Fork\nScottfurt, FM 03330-3230  19 EW       AM   
3227      1931 Andrew Springs\nJamesstad, GU 44502-4798  70 Wo       AM   
...                                                 ...    ...      ...   
6388  16836 Stacy Islands Apt. 493\nMaldonadoville, ...  84 KF       AM   
2499  9996 Harvey Centers Apt. 306\nNew Stevenstad, ...  13 Nm       AM   
5967           95569 Mary Park\nJohnstad, MA 78668-8553  42 Ja       AM   
7214  72162 Brooks Divide Suite 172\nTerrellberg, MS...  90 Ag       AM   
177   054 Hatfield Prairie Apt. 730\nClarkmouth, DE ...  33 IK       PM   
846   873 Emma Divide Apt. 427\nPort Barbara, WA 805...  82 Ve       AM   
4731  72436 Jennifer Park Apt. 541\nGreenberg, NC 87744  11 tT       AM   
9934     52276 Smith Cliffs\nLake Vanessaview, AL 91791  40 nG       AM   
1587    835 Williams Crossroad\nNew Greg, NM 87568-9924  39 AM       AM   
8023                   Unit 6888 Box 8570\nDPO AP 38570  83 ir       PM   
842   970 Natalie Lock Suite 087\nNew Amandatown, VI...  72 sp       PM   
179           99895 Walls Drive\nPort Tristan, HI 96766  72 Io       AM   
7381  40804 Belinda Roads Apt. 186\nWest Nicoleberg,...  30 GH       AM   
2264   040 Ingram Way Suite 602\nEast Matthew, AR 67341  52 WA       AM   
9958                   PSC 8781, Box 4214\nAPO AP 94478  72 Ez       AM   
7533  327 Smith Forks Suite 391\nNew Janetmouth, SC ...  87 QO       PM   
2417  01233 Barnes Landing Apt. 406\nEast Jennifer, ...  65 bo       PM   
2773     455 Hall Lights Apt. 025\nMejiamouth, PR 97762  16 qh       AM   
7482  71176 Swanson Isle Suite 021\nMeganmouth, NH 6...  64 Sk       AM   
3079   7728 Kirby Flats Suite 330\nTracymouth, OK 06688  52 sy       PM   
6441     3307 Franklin Garden\nPort Scottland, UT 79128  68 ie       AM   
4148  5382 Nicole Via Apt. 447\nMartinshire, AS 9397...  74 OR       PM  

In [182]:
df[df['Language']=='en'].count()

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64

In [183]:
df[df['Job']=='Lawyer'].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 470 to 9979
Data columns (total 14 columns):
Address             30 non-null object
Lot                 30 non-null object
AM or PM            30 non-null object
Browser Info        30 non-null object
Company             30 non-null object
Credit Card         30 non-null int64
CC Exp Date         30 non-null object
CC Security Code    30 non-null int64
CC Provider         30 non-null object
Email               30 non-null object
Job                 30 non-null object
IP Address          30 non-null object
Language            30 non-null object
Purchase Price      30 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 3.5+ KB


In [184]:
df[df['Job']=='Lawyer'].count()

Address             30
Lot                 30
AM or PM            30
Browser Info        30
Company             30
Credit Card         30
CC Exp Date         30
CC Security Code    30
CC Provider         30
Email               30
Job                 30
IP Address          30
Language            30
Purchase Price      30
dtype: int64

In [188]:
df['AM or PM'].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [190]:
df['Job'].value_counts().head(5)

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Designer, jewellery              27
Purchasing manager               27
Name: Job, dtype: int64

In [191]:
df[df['Lot']=='90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

In [193]:
df[df["Credit Card"]==4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [194]:
df[(df['CC Provider']=='American Express') & (df['Purchase Price']>95)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

In [195]:
sum(df['CC Exp Date'].apply(lambda x:x[3:])=='25')

1033

In [198]:
df['Email'].apply(lambda x:x.split('@')[1]).value_counts().head(5)

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64

In [2]:
import pandas as pd
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']},index=[0,1,2,3])

In [3]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [7]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                  'B':['B4','B5','B6','B7'],
                  'C':['C4','C5','C6','C7'],'D':['D4','D5','D6','D7']},index=[4,5,6,7])

In [ ]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                  'B':['B8','B9','B10','B11'],
                  'C':['C8','C9','C10','C11'],'D':['D8','D9','D10','D11']},index=[8,9,10,11])

In [9]:
left=pd.DataFrame({'key':['k0','k1','k2','k3'],
                  'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
right=pd.DataFrame({'key':['k0','k1','k2','k3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})


In [10]:
left

key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3

In [11]:
right

key   C   D
0  k0  C0  D0
1  k1  C1  D1
2  k2  C2  D2
3  k3  C3  D3

In [12]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [13]:
pd.concat([df1,df2,df3])

NameError: name 'df3' is not defined

In [23]:
left=pd.DataFrame({'key1':['k0','k0','k1','k2'],'key2':['k0','k1','k0','k1'],
                  'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
right=pd.DataFrame({'key1':['k0','k1','k1','k2'],'key2':['k0','k0','k0','k0'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})

In [30]:
left

key1 key2   A   B
0   k0   k0  A0  B0
1   k0   k1  A1  B1
2   k1   k0  A2  B2
3   k2   k1  A3  B3

In [31]:
right

key1 key2   C   D
0   k0   k0  C0  D0
1   k1   k0  C1  D1
2   k1   k0  C2  D2
3   k2   k0  C3  D3

In [15]:
left


key1 key2   A   B
0   k0   k0  A0  B0
1   k1   k1  A1  B1
2   k2   k0  A2  B2
3   k3   k1  A3  B3

In [16]:
right

key1 key2   C   D
0   k0   k0  C0  D0
1   k1   k0  C1  D1
2   k1   k0  C2  D2
3   k2   k0  C3  D3

In [24]:
pd.merge(left,right, on=['key1','key2'])#...inner join....

key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k0  A2  B2  C1  D1
2   k1   k0  A2  B2  C2  D2

In [26]:
pd.merge(left,right, how='outer' ,on=['key1','key2'])#....Outer join

key1 key2    A    B    C    D
0   k0   k0   A0   B0   C0   D0
1   k0   k1   A1   B1  NaN  NaN
2   k1   k0   A2   B2   C1   D1
3   k1   k0   A2   B2   C2   D2
4   k2   k1   A3   B3  NaN  NaN
5   k2   k0  NaN  NaN   C3   D3

In [27]:
pd.merge(left,right, how='right' ,on=['key1','key2'])

key1 key2    A    B   C   D
0   k0   k0   A0   B0  C0  D0
1   k1   k0   A2   B2  C1  D1
2   k1   k0   A2   B2  C2  D2
3   k2   k0  NaN  NaN  C3  D3

In [29]:
pd.merge(left,right, how='left' ,on=['key1','key2'])

key1 key2   A   B    C    D
0   k0   k0  A0  B0   C0   D0
1   k0   k1  A1  B1  NaN  NaN
2   k1   k0  A2  B2   C1   D1
3   k1   k0  A2  B2   C2   D2
4   k2   k1  A3  B3  NaN  NaN

In [33]:
left=pd.DataFrame({
                  'A':['A0','A1','A2',],'B':['B0','B1','B2']},index=['K0','K1','K2'])
right=pd.DataFrame({'C':['C0','C2','C3'],'D':['D0','D2','D3']},index=['K0','K2','K3'])

In [34]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [35]:
left.join(right,how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3